const STORAGE_KEY='legendHealthManager_v7';
const PREVIOUS_V6_KEY='legendHealthManager_v6';
const PREVIOUS_V5_KEY='legendHealthManager_v5';
const PREVIOUS_KEY='legendHealthManager_v4';
const OLDER_KEY='legendHealthManager_v2';
const OLD_KEY='legendHealth3Day_v1';
const DEVICE_KEY='legendHealthPushDevice_v1';
const days=['before','day1','day2','day3'];
const labels={before:'啟動前',day1:'Day 1',day2:'Day 2',day3:'Day 3'};
const bodyMetrics=[['weight','體重','kg',0.1,false],['bmi','BMI','',0.1,true],['bodyFat','體脂肪率','%',0.1,false],['skeletalMuscle','骨骼肌率','%',0.1,false],['visceral','內臟脂肪','級',1,false],['waist','腰圍','cm',0.1,false]];

const clinicalMetrics=[
 {k:'fastingGlucose',n:'空腹血糖',u:'mg/dL',ideal:'70–99',low:'<70',high:'100–125；≥126 建議醫療評估',rem:'偏低先處理安全；偏高應持續追蹤，單次數值不能自行診斷。'},
 {k:'postMealGlucose',n:'餐後 2 小時血糖',u:'mg/dL',ideal:'<140',low:'<70',high:'140–199；≥200 建議醫療評估',rem:'應由第一口飯開始計時 2 小時；異常需結合臨床狀況評估。'},
 {k:'hba1c',n:'糖化血色素 HbA1c',u:'%',ideal:'<5.7',low:'—',high:'5.7–6.4；≥6.5 建議醫療評估',rem:'反映近 2–3 個月平均血糖；明顯偏高請就醫評估。'},
 {k:'fastingInsulin',n:'空腹胰島素',u:'μU/mL',ideal:'2–10',low:'<2',high:'10–25；>25 偏高',rem:'需搭配空腹血糖、用藥與臨床狀況解讀。'},
 {k:'homaIr',n:'HOMA-IR',u:'',ideal:'<2.0',low:'—',high:'2.0–2.9；≥3.0 偏高',rem:'若同日有空腹血糖與空腹胰島素，系統可自動估算。'},
 {k:'systolic',n:'收縮壓',u:'mmHg',ideal:'<120',low:'—',high:'120–129 偏高；≥130 評估；≥180 緊急警訊',rem:'重複量測仍高應就醫；若 ≥180 且有胸痛、呼吸困難或神經症狀應立即就醫。'},
 {k:'diastolic',n:'舒張壓',u:'mmHg',ideal:'<80',low:'—',high:'≥80 評估；≥90 明顯偏高；≥120 緊急警訊',rem:'請規律量測並記錄趨勢；已服藥者不可自行停藥。'},
 {k:'tg',n:'三酸甘油脂 TG',u:'mg/dL',ideal:'<150',low:'通常無特定低標',high:'≥150 偏高；≥500 應儘速醫療評估',rem:'偏高與代謝及心血管風險相關，建議配合飲食、運動及醫療追蹤。'},
 {k:'ldl',n:'低密度脂蛋白 LDL-C',u:'mg/dL',ideal:'<130',low:'通常無特定低標',high:'≥130 偏高',rem:'依你的指定，本表一般參考值採 <130；個人 LDL-C 目標仍應依整體心血管風險由醫師決定。'},
 {k:'hdl',n:'高密度脂蛋白 HDL-C',u:'mg/dL',ideal:'男 ≥40／女 ≥50',low:'男 <40／女 <50',high:'無固定高標',rem:'偏低代表保護力可能不足，應與 LDL-C、TG 及整體風險一起判讀。'},
 {k:'tc',n:'總膽固醇 TC',u:'mg/dL',ideal:'<200',low:'通常無特定低標',high:'≥200 偏高',rem:'不可只看總膽固醇，需搭配 LDL-C、HDL-C、TG 綜合判讀。'}
];
function homaFor(d){let g=num(getPath(p(),`body.fastingGlucose.${d}`)),i=num(getPath(p(),`body.fastingInsulin.${d}`));return g>0&&i>0?(g*i/405):0}
function clinicalValue(k,d){return k==='homaIr'?(homaFor(d)||''):getPath(p(),`body.${k}.${d}`)}
function clinicalStatus(k,v){v=num(v);if(!v)return'';let g=p().gender;if(k==='fastingGlucose')return v<70?'low':v<=99?'ideal':'high';if(k==='postMealGlucose')return v<70?'low':v<140?'ideal':'high';if(k==='hba1c')return v<5.7?'ideal':'high';if(k==='fastingInsulin')return v<2?'low':v<=10?'ideal':'high';if(k==='homaIr')return v<2?'ideal':'high';if(k==='systolic')return v<120?'ideal':'high';if(k==='diastolic')return v<80?'ideal':'high';if(k==='tg')return v<150?'ideal':'high';if(k==='ldl')return v<130?'ideal':'high';if(k==='hdl'){let lo=g==='女'?50:40;return v<lo?'low':'ideal'}if(k==='tc')return v<200?'ideal':'high';return''}
function renderMedicationRows(){let host=$('#medicationRows');if(!host)return;let meds=p().medical.medications||[];host.innerHTML=meds.map((m,i)=>`<div class="med-row"><input data-med="name" data-med-i="${i}" value="${escapeHtml(m.name||'')}" placeholder="藥物名稱"><input data-med="amount" data-med-i="${i}" value="${escapeHtml(m.amount||'')}" placeholder="數量／劑量，例如 1錠/日"><input data-med="duration" data-med-i="${i}" value="${escapeHtml(m.duration||'')}" placeholder="已用藥多久，例如 6個月"><button class="btn danger no-export" data-med-remove="${i}" type="button">刪除</button></div>`).join('');host.querySelectorAll('[data-med]').forEach(el=>el.addEventListener('input',()=>{p().medical.medications[+el.dataset.medI][el.dataset.med]=el.value;persist()}));host.querySelectorAll('[data-med-remove]').forEach(b=>b.addEventListener('click',()=>{if(p().medical.medications.length>1)p().medical.medications.splice(+b.dataset.medRemove,1);else p().medical.medications=[{name:'',amount:'',duration:''}];persist();renderMedicationRows()}))}

const lifestyleOptions={bowel:['順暢','偏乾','便祕','腹脹','腹瀉','不固定'],sleepQuality:['好','普通','淺眠','易醒','難入睡'],energy:['好','普通','容易疲累','很疲累']};
const feelingOptions=['腹部較不脹','水腫感下降','嘴饞減少','精神變好','排便變順','有飽足感'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function defaultReminder(){return{enabled:false,startTime:'08:00',endTime:'22:00',intervalMinutes:60,timezone:(Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Taipei'),nextReminderAt:''}}
function defaultProfile(i){return{id:i,label:i===0?'我的紀錄':`客戶 ${i}`,name:'',age:'',gender:'',height:'',phone:'',startDate:'',programMode:'3',note:'',body:{},medical:{medicationUse:'',medications:[{name:'',amount:'',duration:''}]},lifestyle:{},protein:{n4:{},food:{}},nutrition:{daily:{},entries:{}},feelings:{},reminder:defaultReminder()}}
function defaultState(){return{active:0,currentView:'dashboard',profiles:Array.from({length:11},(_,i)=>defaultProfile(i))}}
function normalizeState(x){if(!x?.profiles||x.profiles.length!==11)return null;x.profiles=x.profiles.map((r,i)=>({...defaultProfile(i),...r,body:r.body||{},medical:{...defaultProfile(i).medical,...(r.medical||{}),medications:(r.medical?.medications?.length?r.medical.medications:[{name:'',amount:'',duration:''}])},lifestyle:r.lifestyle||{},protein:r.protein||{n4:{},food:{}},nutrition:{daily:{},entries:{},...(r.nutrition||{})},programMode:String(r.programMode||'3'),feelings:r.feelings||{},reminder:{...defaultReminder(),...(r.reminder||{})}}));return x}
function load(){try{for(const key of [STORAGE_KEY,PREVIOUS_V6_KEY,PREVIOUS_V5_KEY,PREVIOUS_KEY,OLDER_KEY,OLD_KEY]){let x=normalizeState(JSON.parse(localStorage.getItem(key)));if(x){x.currentView=x.currentView||'dashboard';localStorage.setItem(STORAGE_KEY,JSON.stringify(x));return x}}}catch{}return defaultState()}
let state=load(); let deferredPrompt=null;
function p(){return state.profiles[state.active]}
function num(v){let n=parseFloat(v);return Number.isFinite(n)?n:0}
function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[k],o)}
function setPath(o,path,v){let ks=path.split('.'),a=o;ks.slice(0,-1).forEach(k=>a=a[k]??={});a[ks.at(-1)]=v}
function persist(show=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show)toast('資料已儲存')}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}
function safe(s){return String(s||'').replace(/[\\/:*?"<>|]/g,'_')}
function currentWeight(){for(const d of ['day3','day2','day1','before']){let w=num(getPath(p(),`body.weight.${d}`));if(w>0)return w}return 0}
function bmiFor(day){let h=num(p().height)/100,w=num(getPath(p(),`body.weight.${day}`));return h>0&&w>0?w/(h*h):0}
function idealText(k){let g=p().gender,h=num(p().height)/100;if(k==='weight')return h?`${(18.5*h*h).toFixed(1)}–${(24*h*h).toFixed(1)} kg`:'BMI 18.5–24（需身高）';if(k==='bmi')return'18.5–24';if(k==='bodyFat')return g==='男'?'約 8–25%':g==='女'?'約 21–33%':'男 8–25%／女 21–33%';if(k==='skeletalMuscle')return g==='男'?'約 33–39%':g==='女'?'約 24–30%':'男 33–39%／女 24–30%';if(k==='visceral')return'1–9 級';if(k==='waist')return g==='男'?'< 90 cm':g==='女'?'< 80 cm':'男 <90／女 <80 cm';return'—'}
function metricValue(k,d){return k==='bmi'?(bmiFor(d)||''):getPath(p(),`body.${k}.${d}`)}
function metricStatus(k,v){v=num(v);if(!v)return'';let g=p().gender,h=num(p().height)/100,lo,hi;if(k==='weight'&&h){lo=18.5*h*h;hi=24*h*h}else if(k==='bmi'){lo=18.5;hi=24}else if(k==='bodyFat'){if(g==='男'){lo=8;hi=25}else if(g==='女'){lo=21;hi=33}else return''}else if(k==='skeletalMuscle'){if(g==='男'){lo=33;hi=39}else if(g==='女'){lo=24;hi=30}else return''}else if(k==='visceral'){lo=1;hi=9}else if(k==='waist'){if(g==='男'){lo=0;hi=89.999}else if(g==='女'){lo=0;hi=79.999}else return''}else return'';return v<lo?'low':v>hi?'high':'ideal'}
function calc(){let w=currentWeight(),g=p().gender;return{w,water:w?Math.round(w*50):0,grams:w?w*2:0,servings:w?(w*2/7):0,fiber:g==='男'?35:g==='女'?25:30,oil:w?(w*.8/5):0,vitamins:6,carbs:w?(w*2/15):0}}
function proteinTotal(d){return num(getPath(p(),`protein.n4.${d}`))+num(getPath(p(),`protein.food.${d}`))}

function programDayCount(){return String(p().programMode||'3')==='14'?14:3}
function nutritionDays(){return Array.from({length:programDayCount()},(_,i)=>`day${i+1}`)}
function nutritionTarget(k){let c=calc();return k==='water'?c.water:k==='protein'?c.servings:k==='fiber'?c.fiber:k==='oil'?c.oil:k==='vitamins'?c.vitamins:k==='carbs'?c.carbs:0}
const nutrientDefs=[
 ['water','💧','水','cc','少量多次補充，建議依目前設定體重 × 50 cc'],
 ['protein','🥚','蛋白質','份','每餐優先蛋白質；1 份約 7 克'],
 ['fiber','🥬','膳食纖維','g','女性約 25g 以上；男性約 35g 以上'],
 ['oil','🥑','好油脂','份','可參考體重 × 0.8 ÷ 5；優先堅果、酪梨、橄欖油'],
 ['vitamins','🍎','維生素與礦物質','份','以 5 份蔬菜＋1 份水果作為每日簡化紀錄'],
 ['carbs','🍠','碳水化合物','份','可參考體重 × 2 ÷ 15；優先原型澱粉']
];
function nutritionEntries(day){let x=getPath(p(),`nutrition.entries.${day}`);return Array.isArray(x)?x:[]}
function nutritionValue(day,k){let entries=nutritionEntries(day);if(entries.length)return entries.reduce((sum,e)=>sum+num(e[k]),0);return num(getPath(p(),`nutrition.daily.${day}.${k}`))}
function nutritionPct(day,k){let t=nutritionTarget(k),v=nutritionValue(day,k);return t?Math.max(0,Math.min(100,Math.round(v/t*100))):0}
function localTimeHHMM(){return new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}
function entrySummary(e){let parts=nutrientDefs.filter(([k])=>num(e[k])>0).map(([k,icon,n,u])=>`${icon} ${n} ${num(e[k])}${u}`);return parts.length?parts.join('｜'):'未填營養數值'}
function saveNutritionEntry(day){let card=document.querySelector(`[data-nutrition-card="${day}"]`);if(!card)return;let timeInput=card.querySelector('[data-entry-time]');let entry={id:(crypto.randomUUID?.()||`n-${Date.now()}-${Math.random().toString(36).slice(2)}`),time:timeInput.value||localTimeHHMM(),createdAt:new Date().toISOString()};let has=false;card.querySelectorAll('[data-entry-nutrient]').forEach(el=>{let v=num(el.value);if(v>0){entry[el.dataset.entryNutrient]=v;has=true}});if(!has){toast('請至少輸入一項飲食或飲水數值');return}let path=`nutrition.entries.${day}`,arr=nutritionEntries(day).slice();arr.push(entry);setPath(p(),path,arr);nutrientDefs.forEach(([k])=>setPath(p(),`nutrition.daily.${day}.${k}`,arr.reduce((sum,e)=>sum+num(e[k]),0)));if(day==='day1'||day==='day2'||day==='day3')setPath(p(),`lifestyle.water.${day}`,arr.reduce((sum,e)=>sum+num(e.water),0));persist();buildNutrition();renderDerived();requestAnimationFrame(()=>{let fresh=document.querySelector(`[data-nutrition-card="${day}"]`);if(!fresh)return;fresh.querySelectorAll('[data-entry-nutrient]').forEach(el=>el.value='');let t=fresh.querySelector('[data-entry-time]');if(t)t.value=localTimeHHMM();let first=fresh.querySelector('[data-entry-nutrient]');if(first)first.focus()});toast('已累計並儲存；輸入欄已清空，可繼續下一筆')}
function removeNutritionEntry(day,id){let arr=nutritionEntries(day).filter(e=>e.id!==id);setPath(p(),`nutrition.entries.${day}`,arr);nutrientDefs.forEach(([k])=>setPath(p(),`nutrition.daily.${day}.${k}`,arr.reduce((sum,e)=>sum+num(e[k]),0)||''));if(day==='day1'||day==='day2'||day==='day3')setPath(p(),`lifestyle.water.${day}`,nutritionValue(day,'water')||'');persist();buildNutrition();renderDerived();toast('已刪除該筆紀錄')}
function buildNutrition(){let host=$('#nutritionGrid');if(!host)return;host.innerHTML=nutritionDays().map((d,i)=>{let entries=nutritionEntries(d);return`<article class="nutrition-day" data-nutrition-card="${d}"><h3>Day ${i+1}<small>${String(p().programMode)==='14'?'習慣養成':'速成紀錄'}</small></h3><div class="nutrition-total-head"><div><div class="water-cup" data-water-cup="${d}"></div><div class="water-percent" data-water-percent="${d}">0%</div></div><div><b>全日自動加總</b><small>${nutrientDefs.map(([k,icon,n,u])=>`${icon} ${n}：<strong data-total="${d}.${k}">0 ${u}</strong>`).join('<br>')}</small></div></div><div class="nutrition-entry-form no-export"><div class="entry-time-row"><label>紀錄時間<input data-entry-time type="time" value="${localTimeHHMM()}"></label><span>輸入本次攝取量後按儲存；系統自動累計，並清空欄位方便下一筆。</span></div><div class="entry-fields">${nutrientDefs.map(([k,icon,n,u])=>`<label>${icon} ${n}<input data-entry-nutrient="${k}" type="number" min="0" step="${k==='water'?50:.1}" inputmode="decimal" placeholder="${u}"></label>`).join('')}</div><button class="btn primary" type="button" data-save-nutrition="${d}">＋ 儲存本次紀錄</button></div><div class="daily-progress-list">${nutrientDefs.map(([k,icon,n,u,tip])=>`<div class="daily-progress-item"><span>${icon} ${n}</span><div><div class="nutrient-progress"><i data-nutrition-bar="${d}.${k}"></i></div><small>目標：<span data-nutrition-target="${k}"></span>｜${tip}</small></div></div>`).join('')}</div><div class="nutrition-log"><h4>當日紀錄 <span>${entries.length} 筆</span></h4>${entries.length?entries.slice().sort((a,b)=>String(a.time).localeCompare(String(b.time))).map(e=>`<div class="nutrition-log-row"><time>${escapeHtml(e.time||'--:--')}</time><div>${entrySummary(e)}</div><button class="btn danger no-export" type="button" data-remove-nutrition="${d}" data-entry-id="${escapeHtml(e.id)}">刪除</button></div>`).join(''):'<div class="empty-log">尚無紀錄</div>'}</div></article>`}).join('');host.querySelectorAll('[data-save-nutrition]').forEach(b=>b.addEventListener('click',()=>saveNutritionEntry(b.dataset.saveNutrition)));host.querySelectorAll('[data-remove-nutrition]').forEach(b=>b.addEventListener('click',()=>removeNutritionEntry(b.dataset.removeNutrition,b.dataset.entryId)));renderNutritionProgress()}
function renderNutritionProgress(){document.querySelectorAll('[data-nutrition-target]').forEach(el=>{let k=el.dataset.nutritionTarget,t=nutritionTarget(k);el.textContent=t?`${Number(t).toFixed(k==='water'?0:1)} ${nutrientDefs.find(x=>x[0]===k)[3]}`:'請先輸入體重'});nutritionDays().forEach(d=>{nutrientDefs.forEach(([k,,,u])=>{let v=nutritionValue(d,k),pct=nutritionPct(d,k),bar=document.querySelector(`[data-nutrition-bar="${d}.${k}"]`),tot=document.querySelector(`[data-total="${d}.${k}"]`);if(bar)bar.style.width=`${pct}%`;if(tot)tot.textContent=`${k==='water'?Math.round(v):Number(v.toFixed(1))} ${u}`});let cup=document.querySelector(`[data-water-cup="${d}"]`),pct=nutritionPct(d,'water'),txt=document.querySelector(`[data-water-percent="${d}"]`);if(cup)cup.style.setProperty('--fill',`${pct}%`);if(txt)txt.textContent=`${Math.round(nutritionValue(d,'water'))} cc｜${pct}%`})}
function renderNutritionPrinciples(){let c=calc(),e=$('#nutritionPrinciples');if(!e)return;e.innerHTML=`<div class="principle"><b>💧 水分</b><small>${c.water?c.water.toLocaleString()+' cc/天':'輸入體重後計算'}</small></div><div class="principle"><b>🥚 蛋白質</b><small>${c.servings?c.servings.toFixed(1)+' 份/天（約 '+c.grams.toFixed(0)+'g）':'輸入體重後計算'}</small></div><div class="principle"><b>🥬 膳食纖維</b><small>${c.fiber} g/天</small></div><div class="principle"><b>🥑 好油脂</b><small>${c.oil?c.oil.toFixed(1)+' 份/天':'輸入體重後計算'}</small></div><div class="principle"><b>🍎 維生素與礦物質</b><small>蔬菜 5 份＋水果 1 份</small></div><div class="principle"><b>🍠 碳水化合物</b><small>${c.carbs?c.carbs.toFixed(1)+' 份/天':'輸入體重後計算'}</small></div>`;document.querySelectorAll('[data-program]').forEach(b=>b.classList.toggle('active',b.dataset.program===String(p().programMode||'3')))}

function format(v,suffix=''){return v!==''&&v!=null?`${v}${suffix}`:'—'}
function build(){
 const sel=$('#clientSelect'); state.profiles.forEach((x,i)=>{let o=document.createElement('option');o.value=i;sel.append(o)});
 bodyMetrics.forEach(([k,n,u,step,derived])=>{let tr=document.createElement('tr');tr.dataset.metric=k;tr.innerHTML=`<th>${n}<small>${u||''}</small><em class="ideal-text" data-ideal="${k}"></em></th>`+days.map(d=>derived?`<td><span class="derived-value" data-derived="${k}.${d}">—</span></td>`:`<td><input data-path="body.${k}.${d}" data-metric="${k}" data-day="${d}" type="number" inputmode="decimal" step="${step}" placeholder="${u}"></td>`).join('');$('#bodyRows').append(tr)});
 clinicalMetrics.forEach(m=>{let tr=document.createElement('tr');tr.innerHTML=`<th>${m.n}<small>${m.u}</small><em class="ideal-text">理想：${m.ideal}｜低標：${m.low}｜高標：${m.high}</em></th>`+days.map(d=>m.k==='homaIr'?`<td><span class="derived-value" data-clinical-derived="${m.k}.${d}">—</span></td>`:`<td><input data-path="body.${m.k}.${d}" data-clinical="${m.k}" data-day="${d}" type="number" inputmode="decimal" step="0.1" placeholder="${m.u}"></td>`).join('')+`<td class="health-reminder">${m.rem}</td>`;$('#clinicalRows').append(tr)});
 days.forEach(d=>{let c=document.createElement('article');c.className='day-card';c.innerHTML=`<h3>${labels[d]}</h3><div class="metric"><label>飲水量（cc）</label>${d==='before'?`<input data-path="lifestyle.water.${d}" type="number" min="0" step="50" inputmode="numeric">`:`<span class="derived-value" data-lifestyle-water-total="${d}">—</span><small class="field-note">由六大營養素的分次飲水紀錄自動加總</small>`}</div><div class="metric"><label>排便狀況</label><div class="checks">${lifestyleOptions.bowel.map(x=>`<label><input data-group="lifestyle.bowel.${d}" type="checkbox" value="${x}">${x}</label>`).join('')}</div></div><div class="metric"><label>睡眠時數</label><input data-path="lifestyle.sleepHours.${d}" type="number" min="0" max="24" step="0.5"></div><div class="metric"><label>睡眠品質</label><div class="checks">${lifestyleOptions.sleepQuality.map(x=>`<label><input data-path="lifestyle.sleepQuality.${d}" name="sleep-${d}" type="radio" value="${x}">${x}</label>`).join('')}</div></div><div class="metric"><label>白天精神</label><div class="checks">${lifestyleOptions.energy.map(x=>`<label><input data-path="lifestyle.energy.${d}" name="energy-${d}" type="radio" value="${x}">${x}</label>`).join('')}</div></div>`;$('#lifestyleGrid').append(c)});
 ['day1','day2','day3'].forEach(d=>{let c=document.createElement('article');c.className='feeling-card';c.innerHTML=`<h3>${labels[d]}</h3><div class="checks">${feelingOptions.map(x=>`<label><input data-group="feelings.${d}.checks" type="checkbox" value="${x}">${x}</label>`).join('')}</div><textarea data-path="feelings.${d}.other" placeholder="其他感受或補充…"></textarea>`;$('#feelingGrid').append(c)});
 $$('[data-path]').forEach(el=>el.addEventListener(el.type==='radio'?'change':'input',()=>{if(el.type==='radio'&&!el.checked)return;setPath(p(),el.dataset.path,el.value);persist();renderDerived()}));
 $$('[data-group]').forEach(el=>el.addEventListener('change',()=>{let path=el.dataset.group,arr=$$(`[data-group="${CSS.escape(path)}"]`).filter(x=>x.checked).map(x=>x.value);setPath(p(),path,arr);persist();renderDerived()}));
 $$('[data-root]').forEach(el=>el.addEventListener('input',()=>{p()[el.dataset.root]=el.value;persist();renderDerived()}));
}
function updateClientOptions(){let sel=$('#clientSelect');state.profiles.forEach((x,i)=>sel.options[i].textContent=i===0?`我的紀錄${x.name?'｜'+x.name:''}`:`客戶 ${i}${x.name?'｜'+x.name:''}`);sel.value=state.active}
function renderInputs(){let x=p();$$('[data-root]').forEach(el=>el.value=x[el.dataset.root]??'');$$('[data-path]').forEach(el=>{let v=getPath(x,el.dataset.path)??'';if(el.type==='radio')el.checked=String(v)===el.value;else el.value=v});$$('[data-group]').forEach(el=>{let a=getPath(x,el.dataset.group)||[];el.checked=Array.isArray(a)&&a.includes(el.value)})}
function renderDerived(){let x=p(),c=calc();updateClientOptions();$('#dashGreeting').textContent=x.name?`${x.name}｜${x.programMode==='14'?'14 天習慣養成':'3 天速成'}`:(x.programMode==='14'?'14 天習慣養成':'3 天速成');$('#dashName').textContent=x.name||'—';$('#dashAge').textContent=`年齡 ${x.age||'—'}`;$('#dashWater').textContent=c.water?`${c.water.toLocaleString()} cc`:'—';$('#dashProtein').textContent=c.servings?`${c.servings.toFixed(1)} 份`:'—';
 $$('[data-print="name"]').forEach(e=>e.textContent=x.name||'—');$$('[data-print="water"]').forEach(e=>e.textContent=c.water?`${c.water.toLocaleString()} cc / 天`:'—');$$('[data-print="protein"]').forEach(e=>e.textContent=c.servings?`${c.servings.toFixed(1)} 份 / 天（約 ${c.grams.toFixed(0)} 克）`:'—');
 $$('[data-ideal]').forEach(e=>e.textContent=`理想：${idealText(e.dataset.ideal)}`);days.forEach(d=>{let e=$(`[data-derived="bmi.${d}"]`),v=bmiFor(d);if(e){e.textContent=v?v.toFixed(1):'—';e.className=`derived-value ${metricStatus('bmi',v)}`}});$$('[data-metric]').forEach(e=>{let cls=metricStatus(e.dataset.metric,e.value);e.classList.remove('ideal','low','high');if(cls)e.classList.add(cls)});days.forEach(d=>{let e=$(`[data-clinical-derived="homaIr.${d}"]`),v=homaFor(d);if(e){e.textContent=v?v.toFixed(2):'—';e.className=`derived-value ${clinicalStatus('homaIr',v)}`}});$$('[data-clinical]').forEach(e=>{let cls=clinicalStatus(e.dataset.clinical,e.value);e.classList.remove('ideal','low','high');if(cls)e.classList.add(cls)});$('#idealGuide').innerHTML=`<b>個人理想值參考</b><span>性別：${x.gender||'未選擇'}</span><span>身高：${x.height?x.height+' cm':'未填'}</span><span>BMI：18.5–24</span><span>腰圍：${idealText('waist')}</span><span>體脂：${idealText('bodyFat')}</span><span>骨骼肌：${idealText('skeletalMuscle')}</span><span>內臟脂肪：1–9 級</span>`;
 ['day1','day2','day3'].forEach(d=>{let e=document.querySelector(`[data-lifestyle-water-total="${d}"]`);if(e)e.textContent=nutritionValue(d,'water')?`${Math.round(nutritionValue(d,'water'))} cc`:'—'});
 let wb=num(getPath(x,'body.weight.before')),w3=num(getPath(x,'body.weight.day3'));$('#dashWeightChange').textContent=wb&&w3?`${(w3-wb)>0?'+':''}${(w3-wb).toFixed(1)} kg`:'—';
 let filled=0,total=0,pct=0;if(x.programMode==='14'){let nd=nutritionDays();total=nd.length*nutrientDefs.length;nd.forEach(d=>nutrientDefs.forEach(([k])=>{if(nutritionValue(d,k)>0)filled++}));pct=Math.min(100,Math.round(filled/total*100));$('#daySummary').innerHTML=nd.map((d,i)=>{let water=nutritionValue(d,'water'),protein=nutritionValue(d,'protein');return`<div class="day-pill"><b>Day ${i+1}</b><small>水 ${water?water+' cc':'—'}<br>蛋白質 ${protein?protein+' 份':'—'}</small></div>`}).join('')}else{total=bodyMetrics.length*4+4*4+6*3+3;bodyMetrics.forEach(([k,,, ,derived])=>days.forEach(d=>{let v=derived?metricValue(k,d):getPath(x,`body.${k}.${d}`);if(v!==undefined&&v!=='')filled++}));days.forEach(d=>{['water','sleepHours','sleepQuality','energy'].forEach(k=>{if(getPath(x,`lifestyle.${k}.${d}`))filled++})});nutritionDays().forEach(d=>nutrientDefs.forEach(([k])=>{if(nutritionValue(d,k)>0)filled++}));['day1','day2','day3'].forEach(d=>{if((getPath(x,`feelings.${d}.checks`)||[]).length)filled++});pct=Math.min(100,Math.round(filled/total*100));$('#daySummary').innerHTML=days.map(d=>{let w=getPath(x,`body.weight.${d}`),water=getPath(x,`lifestyle.water.${d}`);return`<div class="day-pill"><b>${labels[d]}</b><small>${w?`${w} kg`:'未填體重'}<br>${water?`${water} cc`:'未填飲水'}</small></div>`}).join('')}$('#completionText').textContent=`${pct}%`;$('#completionBar').style.width=`${pct}%`;let ph=document.querySelector('.progress-card h2');if(ph)ph.textContent=x.programMode==='14'?'14 天習慣養成進度':'3 天速成進度';
 $('#comparisonGrid').innerHTML=bodyMetrics.map(([k,n,u])=>{let a=num(metricValue(k,'before')),b=num(metricValue(k,'day3')),diff=a&&b?b-a:null;return`<div class="compare-item"><span>${n}</span><small>理想 ${idealText(k)}</small><b>${diff===null?'—':`${diff>0?'+':''}${Number.isInteger(diff)?diff:diff.toFixed(1)} ${u}`}</b></div>`}).join('');
 renderNutritionPrinciples();renderNutritionProgress();
 renderReport();
}
function renderReport(){let x=p(),c=calc();$('#reportName').textContent=x.name||'—';$('#reportAge').textContent=x.age||'—';$('#reportGender').textContent=x.gender||'—';$('#reportHeight').textContent=x.height?`${x.height} cm`:'—';$('#reportWater').textContent=c.water?`${c.water.toLocaleString()} cc`:'—';$('#reportProtein').textContent=c.servings?`${c.servings.toFixed(1)} 份`:'—';$('#reportDate').textContent=x.startDate||'—';$('#reportBodyRows').innerHTML=bodyMetrics.map(([k,n,u])=>`<tr><th>${n}<small>${u}</small><em class="ideal-text">理想：${idealText(k)}</em></th>${days.map(d=>{let v=metricValue(k,d),st=metricStatus(k,v);return`<td class="${st}">${k==='bmi'&&v?num(v).toFixed(1):format(v)}</td>`}).join('')}</tr>`).join('');$('#reportClinicalRows').innerHTML=clinicalMetrics.map(m=>`<tr><th>${m.n}<small>${m.u}</small><em class="ideal-text">理想：${m.ideal}</em></th>${days.map(d=>{let v=clinicalValue(m.k,d),st=clinicalStatus(m.k,v);return`<td class="${st}">${m.k==='homaIr'&&v?num(v).toFixed(2):format(v)}</td>`}).join('')}<td class="health-reminder">${m.rem}</td></tr>`).join('');$('#reportMedication').innerHTML=`<b>是否服用藥物：</b>${x.medical?.medicationUse||'未填'}<br>`+(x.medical?.medications||[]).filter(m=>m.name||m.amount||m.duration).map(m=>`${escapeHtml(m.name||'未填藥名')}｜${escapeHtml(m.amount||'未填數量/劑量')}｜${escapeHtml(m.duration||'未填時間')}`).join('<br>')||'—';$('#reportLifestyle').innerHTML=['day1','day2','day3'].map(d=>`<div class="report-mini"><b>${labels[d]}</b>飲水：${format(getPath(x,`lifestyle.water.${d}`),' cc')}<br>排便：${(getPath(x,`lifestyle.bowel.${d}`)||[]).join('、')||'—'}<br>睡眠：${format(getPath(x,`lifestyle.sleepHours.${d}`),' 小時')}／${getPath(x,`lifestyle.sleepQuality.${d}`)||'—'}<br>精神：${getPath(x,`lifestyle.energy.${d}`)||'—'}</div>`).join('');$('#reportNutritionGrid').innerHTML=nutritionDays().map((d,i)=>`<div class="report-nutrition-day"><b>Day ${i+1}｜全日加總</b>${nutrientDefs.map(([k,,n,u])=>`${n}：${nutritionValue(d,k)?`${k==='water'?Math.round(nutritionValue(d,k)):Number(nutritionValue(d,k).toFixed(1))} ${u}`:'—'}（${nutritionPct(d,k)}%）`).join('<br>')}<div class="report-entry-list">${nutritionEntries(d).length?nutritionEntries(d).slice().sort((a,b)=>String(a.time).localeCompare(String(b.time))).map(e=>`<span><time>${escapeHtml(e.time||'--:--')}</time> ${entrySummary(e)}</span>`).join(''):'<span>尚無分次紀錄</span>'}</div></div>`).join('');$('#reportFeelings').innerHTML=['day1','day2','day3'].map(d=>`<div class="report-mini"><b>${labels[d]}</b>${(getPath(x,`feelings.${d}.checks`)||[]).join('、')||'—'}${getPath(x,`feelings.${d}.other`)?`<br>其他：${escapeHtml(getPath(x,`feelings.${d}.other`))}`:''}</div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderInputs();renderMedicationRows();buildNutrition();renderNutritionPrinciples();let mu=$('#medicationUse');if(mu)mu.value=p().medical.medicationUse||'';renderDerived();renderReminder();showView(state.currentView||'dashboard',false)}
function showView(v,save=true){state.currentView=v;$$('.view').forEach(e=>e.classList.toggle('active',e.id===`view-${v}`));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(save)persist();$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function cloneForExport(el){let clone=el.cloneNode(true);clone.querySelectorAll('.no-export,button').forEach(e=>e.remove());clone.querySelectorAll('input,textarea,select').forEach(ctrl=>{let span=document.createElement('span');span.className='export-value';if(ctrl.type==='checkbox'||ctrl.type==='radio')span.textContent=ctrl.checked?`☑ ${ctrl.value}`:'☐';else if(ctrl.tagName==='SELECT')span.textContent=ctrl.selectedOptions[0]?.textContent||'—';else span.textContent=ctrl.value||'—';ctrl.replaceWith(span)});return clone}
async function captureCurrent(){let source=$('.view.active');let host=document.createElement('div');host.style.cssText='position:fixed;left:-100000px;top:0;width:794px;background:white;z-index:-1';let clone=cloneForExport(source);clone.style.cssText+=';display:block;width:794px;min-height:1123px;border:0;box-shadow:none;border-radius:0;padding:28px';host.append(clone);document.body.append(host);try{return await html2canvas(clone,{scale:2,useCORS:true,backgroundColor:'#fff',windowWidth:794,scrollX:0,scrollY:0})}finally{host.remove()}}
function filename(ext){let title=$$(`#nav button`).find(b=>b.dataset.view===state.currentView)?.textContent.trim().replace(/^\S+\s*/,'')||'紀錄';return `傳奇健康管理學院_${safe(p().name||p().label)}_${safe(title)}.${ext}`}
async function exportPNG(share=false){$('#exportMask').classList.add('show');try{let canvas=await captureCurrent(),blob=await new Promise(r=>canvas.toBlob(r,'image/png',1)),file=new File([blob],filename('png'),{type:'image/png'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'傳奇健康管理學院紀錄',files:[file]});return}let a=document.createElement('a');a.download=file.name;a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast('PNG 已下載')}finally{$('#exportMask').classList.remove('show')}}
async function exportPDF(share=false){$('#exportMask').classList.add('show');try{let canvas=await captureCurrent(),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),pw=210,ph=297,margin=6,usableW=pw-margin*2,usableH=ph-margin*2,imgW=usableW,imgH=canvas.height*imgW/canvas.width,img=canvas.toDataURL('image/jpeg',.94);if(imgH<=usableH){pdf.addImage(img,'JPEG',margin,margin,imgW,imgH)}else{let pageCanvas=document.createElement('canvas'),ctx=pageCanvas.getContext('2d'),pxPerMm=canvas.width/usableW,pageHpx=Math.floor(usableH*pxPerMm);pageCanvas.width=canvas.width;let y=0,page=0;while(y<canvas.height){let slice=Math.min(pageHpx,canvas.height-y);pageCanvas.height=slice;ctx=pageCanvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,pageCanvas.width,pageCanvas.height);ctx.drawImage(canvas,0,y,canvas.width,slice,0,0,canvas.width,slice);if(page++)pdf.addPage();pdf.addImage(pageCanvas.toDataURL('image/jpeg',.94),'JPEG',margin,margin,usableW,slice/pxPerMm);y+=slice}}let blob=pdf.output('blob'),file=new File([blob],filename('pdf'),{type:'application/pdf'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'傳奇健康管理學院紀錄',files:[file]});return}pdf.save(file.name);toast('PDF 已下載')}finally{$('#exportMask').classList.remove('show')}}

function getDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=(crypto.randomUUID?.()||`dev-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem(DEVICE_KEY,id)}return id}
function pushSupported(){return 'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window&&(location.protocol==='https:'||location.hostname==='localhost')}
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function getPushRegistration(){if(!pushSupported())throw new Error('此瀏覽器或目前網址不支援背景推播');await navigator.serviceWorker.register('sw.js');return navigator.serviceWorker.ready}
async function getOrCreateSubscription(requestPermission=true){
 if(!pushSupported())throw new Error('此裝置不支援 Web Push，或網站尚未使用 HTTPS');
 if(Notification.permission==='denied')throw new Error('通知權限已被封鎖，請到手機的網站／APP通知設定重新允許');
 if(Notification.permission!=='granted'&&requestPermission){const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('尚未允許通知權限')}
 const reg=await getPushRegistration();let sub=await reg.pushManager.getSubscription();if(sub)return sub;
 const r=await fetch('/api/push/public-key');const j=await r.json();if(!r.ok)throw new Error(j.error||'無法取得推播金鑰');
 return reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(j.publicKey)});
}
function reminderSettings(){return p().reminder||(p().reminder=defaultReminder())}
function localNextText(iso){if(!iso)return'尚未設定下一次提醒';let d=new Date(iso);if(Number.isNaN(d.getTime()))return'尚未設定下一次提醒';return`下一次背景提醒：約 ${d.toLocaleString('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`}
function renderReminder(){
 const r=reminderSettings(),c=calc();
 const name=$('#reminderClientName'),water=$('#reminderTargetWater'),badge=$('#pushStatusBadge');if(!name)return;
 name.textContent=p().name||p().label;water.textContent=c.water?`${c.water.toLocaleString()} cc / 天`:'請先輸入體重';
 $('#reminderStart').value=r.startTime||'08:00';$('#reminderEnd').value=r.endTime||'22:00';$('#reminderInterval').value=String(r.intervalMinutes||60);$('#reminderTimezone').value=r.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Taipei';$('#reminderEnabled').checked=!!r.enabled;$('#nextReminderText').textContent=localNextText(r.nextReminderAt);
 badge.className='push-badge';
 if(!pushSupported()){badge.textContent='此環境不支援';badge.classList.add('off');$('#notificationHelp').classList.add('push-error')}
 else if(Notification.permission==='denied'){badge.textContent='通知被封鎖';badge.classList.add('off')}
 else if(Notification.permission==='granted'&&r.enabled){badge.textContent='背景提醒已開啟';badge.classList.add('on')}
 else if(Notification.permission==='granted'){badge.textContent='通知已連線';badge.classList.add('warn')}
 else{badge.textContent='尚未允許通知'}
}
function readReminderForm(){let r=reminderSettings();r.startTime=$('#reminderStart').value||'08:00';r.endTime=$('#reminderEnd').value||'22:00';r.intervalMinutes=Number($('#reminderInterval').value)||60;r.timezone=$('#reminderTimezone').value||Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Taipei';r.enabled=$('#reminderEnabled').checked;persist();return r}
async function postReminderSettings(subscription){
 const r=readReminderForm(),c=calc();
 const resp=await fetch('/api/push/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:getDeviceId(),profileId:state.active,clientName:p().name||p().label,subscription:subscription.toJSON?subscription.toJSON():subscription,enabled:r.enabled,startTime:r.startTime,endTime:r.endTime,intervalMinutes:r.intervalMinutes,timezone:r.timezone,targetWater:c.water})});
 const j=await resp.json();if(!resp.ok)throw new Error(j.error||'提醒設定儲存失敗');r.nextReminderAt=j.nextReminderAt||'';persist();renderReminder();return j
}
async function enablePush(){
 const btn=$('#enablePushBtn');btn.disabled=true;btn.textContent='正在連線…';
 try{const sub=await getOrCreateSubscription(true);await postReminderSettings(sub);toast('手機通知已成功連線');renderReminder()}catch(e){alert(e.message||'通知連線失敗')}finally{btn.disabled=false;btn.textContent='允許通知並連線'}
}
async function saveReminder(){
 const r=readReminderForm();const btn=$('#saveReminderBtn');btn.disabled=true;
 try{
   if(r.enabled){const sub=await getOrCreateSubscription(true);await postReminderSettings(sub);toast('背景喝水提醒已儲存')}
   else{
     await fetch('/api/push/disable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:getDeviceId(),profileId:state.active})});r.nextReminderAt='';persist();renderReminder();toast('此紀錄的喝水提醒已關閉')
   }
 }catch(e){alert(e.message||'儲存提醒失敗')}finally{btn.disabled=false}
}
async function testPush(){
 const btn=$('#testPushBtn');btn.disabled=true;btn.textContent='傳送中…';
 try{const sub=await getOrCreateSubscription(true);await postReminderSettings(sub);const resp=await fetch('/api/push/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:getDeviceId(),profileId:state.active})});const j=await resp.json();if(!resp.ok)throw new Error(j.error||'測試通知失敗');toast('測試通知已送出，請查看手機通知')}
 catch(e){alert(e.message||'測試通知失敗')}finally{btn.disabled=false;btn.textContent='傳送測試通知'}
}

function backup(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`傳奇健康管理學院_資料備份_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x?.profiles||x.profiles.length!==11)throw 0;if(!confirm('確定以備份檔覆蓋目前全部資料？'))return;state=x;persist();render();toast('還原完成')}catch{alert('備份檔格式不正確')}};r.readAsText(file)}
const startupParams=new URLSearchParams(location.search);const startupProfile=Number(startupParams.get('profile'));if(Number.isInteger(startupProfile)&&startupProfile>=0&&startupProfile<11)state.active=startupProfile;const startupView=startupParams.get('view');if(startupView&&['dashboard','profile','body','lifestyle','reminder','nutrition','feelings','report','backup'].includes(startupView))state.currentView=startupView;build();render();
$('#clientSelect').addEventListener('change',e=>{state.active=+e.target.value;persist();render()});$$('#nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#quickSaveBtn').addEventListener('click',()=>persist(true));$('#exportPngBtn').addEventListener('click',()=>exportPNG());$('#exportPdfBtn').addEventListener('click',()=>exportPDF());$('#shareBtn').addEventListener('click',async()=>{try{await exportPDF(true)}catch(e){if(e?.name!=='AbortError'){toast('此裝置不支援 PDF 分享，改分享 PNG');try{await exportPNG(true)}catch{}}}});$('#clearClientBtn').addEventListener('click',async()=>{if(confirm('確定清除此組客戶全部資料？此動作無法復原。')){try{await fetch('/api/push/disable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:getDeviceId(),profileId:state.active})})}catch{}state.profiles[state.active]=defaultProfile(state.active);persist();render();toast('已清除；此紀錄的喝水提醒也已關閉')}});$('#backupBtn').addEventListener('click',backup);$('#restoreInput').addEventListener('change',e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''});
$('#enablePushBtn').addEventListener('click',enablePush);$('#saveReminderBtn').addEventListener('click',saveReminder);$('#testPushBtn').addEventListener('click',testPush);['#reminderStart','#reminderEnd','#reminderInterval','#reminderEnabled'].forEach(sel=>$(sel).addEventListener('change',()=>{readReminderForm();renderReminder()}));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

$('#medicationUse')?.addEventListener('change',e=>{p().medical.medicationUse=e.target.value;persist()});$('#addMedicationBtn')?.addEventListener('click',()=>{p().medical.medications.push({name:'',amount:'',duration:''});persist();renderMedicationRows()});

$$('[data-program]').forEach(b=>b.addEventListener('click',()=>{p().programMode=b.dataset.program;persist();renderInputs();buildNutrition();renderNutritionPrinciples();renderDerived();toast(b.dataset.program==='14'?'已切換為 14 天習慣養成':'已切換為 3 天速成')}));
$('#programMode')?.addEventListener('change',()=>{p().programMode=$('#programMode').value;persist();buildNutrition();renderNutritionPrinciples();renderDerived()});
