const STORAGE_KEY='legendHealthManager_v2';
const OLD_KEY='legendHealth3Day_v1';
const days=['before','day1','day2','day3'];
const labels={before:'啟動前',day1:'Day 1',day2:'Day 2',day3:'Day 3'};
const bodyMetrics=[['weight','體重','kg',0.1],['bodyFat','體脂肪率','%',0.1],['muscle','肌肉量','kg',0.1],['visceral','內臟脂肪','級',1],['waist','腰圍','cm',0.1]];
const lifestyleOptions={bowel:['順暢','偏乾','便祕','腹脹','腹瀉','不固定'],sleepQuality:['好','普通','淺眠','易醒','難入睡'],energy:['好','普通','容易疲累','很疲累']};
const feelingOptions=['腹部較不脹','水腫感下降','嘴饞減少','精神變好','排便變順','有飽足感'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function defaultProfile(i){return{id:i,label:i===0?'我的紀錄':`客戶 ${i}`,name:'',age:'',phone:'',startDate:'',note:'',body:{},lifestyle:{},protein:{n4:{},food:{}},feelings:{}}}
function defaultState(){return{active:0,currentView:'dashboard',profiles:Array.from({length:11},(_,i)=>defaultProfile(i))}}
function load(){try{let x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x?.profiles?.length===11)return x;let old=JSON.parse(localStorage.getItem(OLD_KEY));if(old?.profiles?.length===11){old.currentView='dashboard';localStorage.setItem(STORAGE_KEY,JSON.stringify(old));return old}}catch{}return defaultState()}
let state=load(); let deferredPrompt=null;
function p(){return state.profiles[state.active]}
function num(v){let n=parseFloat(v);return Number.isFinite(n)?n:0}
function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[k],o)}
function setPath(o,path,v){let ks=path.split('.'),a=o;ks.slice(0,-1).forEach(k=>a=a[k]??={});a[ks.at(-1)]=v}
function persist(show=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show)toast('資料已儲存')}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}
function safe(s){return String(s||'').replace(/[\\/:*?"<>|]/g,'_')}
function currentWeight(){for(const d of ['day3','day2','day1','before']){let w=num(getPath(p(),`body.weight.${d}`));if(w>0)return w}return 0}
function calc(){let w=currentWeight();return{w,water:w?Math.round(w*50):0,grams:w?w*2:0,servings:w?(w*2/7):0}}
function proteinTotal(d){return num(getPath(p(),`protein.n4.${d}`))+num(getPath(p(),`protein.food.${d}`))}
function format(v,suffix=''){return v!==''&&v!=null?`${v}${suffix}`:'—'}
function build(){
 const sel=$('#clientSelect'); state.profiles.forEach((x,i)=>{let o=document.createElement('option');o.value=i;sel.append(o)});
 bodyMetrics.forEach(([k,n,u,step])=>{let tr=document.createElement('tr');tr.innerHTML=`<th>${n}<small>${u}</small></th>`+days.map(d=>`<td><input data-path="body.${k}.${d}" type="number" inputmode="decimal" step="${step}" placeholder="${u}"></td>`).join('');$('#bodyRows').append(tr)});
 days.forEach(d=>{let c=document.createElement('article');c.className='day-card';c.innerHTML=`<h3>${labels[d]}</h3><div class="metric"><label>飲水量（cc）</label><input data-path="lifestyle.water.${d}" type="number" min="0" step="50" inputmode="numeric"></div><div class="metric"><label>排便狀況</label><div class="checks">${lifestyleOptions.bowel.map(x=>`<label><input data-group="lifestyle.bowel.${d}" type="checkbox" value="${x}">${x}</label>`).join('')}</div></div><div class="metric"><label>睡眠時數</label><input data-path="lifestyle.sleepHours.${d}" type="number" min="0" max="24" step="0.5"></div><div class="metric"><label>睡眠品質</label><div class="checks">${lifestyleOptions.sleepQuality.map(x=>`<label><input data-path="lifestyle.sleepQuality.${d}" name="sleep-${d}" type="radio" value="${x}">${x}</label>`).join('')}</div></div><div class="metric"><label>白天精神</label><div class="checks">${lifestyleOptions.energy.map(x=>`<label><input data-path="lifestyle.energy.${d}" name="energy-${d}" type="radio" value="${x}">${x}</label>`).join('')}</div></div>`;$('#lifestyleGrid').append(c)});
 ['day1','day2','day3'].forEach(d=>{let c=document.createElement('article');c.className='feeling-card';c.innerHTML=`<h3>${labels[d]}</h3><div class="checks">${feelingOptions.map(x=>`<label><input data-group="feelings.${d}.checks" type="checkbox" value="${x}">${x}</label>`).join('')}</div><textarea data-path="feelings.${d}.other" placeholder="其他感受或補充…"></textarea>`;$('#feelingGrid').append(c)});
 $$('[data-path]').forEach(el=>el.addEventListener(el.type==='radio'?'change':'input',()=>{if(el.type==='radio'&&!el.checked)return;setPath(p(),el.dataset.path,el.value);persist();renderDerived()}));
 $$('[data-group]').forEach(el=>el.addEventListener('change',()=>{let path=el.dataset.group,arr=$$(`[data-group="${CSS.escape(path)}"]`).filter(x=>x.checked).map(x=>x.value);setPath(p(),path,arr);persist();renderDerived()}));
 $$('[data-root]').forEach(el=>el.addEventListener('input',()=>{p()[el.dataset.root]=el.value;persist();renderDerived()}));
}
function updateClientOptions(){let sel=$('#clientSelect');state.profiles.forEach((x,i)=>sel.options[i].textContent=i===0?`我的紀錄${x.name?'｜'+x.name:''}`:`客戶 ${i}${x.name?'｜'+x.name:''}`);sel.value=state.active}
function renderInputs(){let x=p();$$('[data-root]').forEach(el=>el.value=x[el.dataset.root]||'');$$('[data-path]').forEach(el=>{let v=getPath(x,el.dataset.path)??'';if(el.type==='radio')el.checked=String(v)===el.value;else el.value=v});$$('[data-group]').forEach(el=>{let a=getPath(x,el.dataset.group)||[];el.checked=Array.isArray(a)&&a.includes(el.value)})}
function renderDerived(){let x=p(),c=calc();updateClientOptions();$('#dashGreeting').textContent=x.name?`${x.name}｜三天體態啟動紀錄`:'三天體態啟動紀錄';$('#dashName').textContent=x.name||'—';$('#dashAge').textContent=`年齡 ${x.age||'—'}`;$('#dashWater').textContent=c.water?`${c.water.toLocaleString()} cc`:'—';$('#dashProtein').textContent=c.servings?`${c.servings.toFixed(1)} 份`:'—';
 $$('[data-print="name"]').forEach(e=>e.textContent=x.name||'—');$$('[data-print="water"]').forEach(e=>e.textContent=c.water?`${c.water.toLocaleString()} cc / 天`:'—');$$('[data-print="protein"]').forEach(e=>e.textContent=c.servings?`${c.servings.toFixed(1)} 份 / 天（約 ${c.grams.toFixed(0)} 克）`:'—');
 let wb=num(getPath(x,'body.weight.before')),w3=num(getPath(x,'body.weight.day3'));$('#dashWeightChange').textContent=wb&&w3?`${(w3-wb)>0?'+':''}${(w3-wb).toFixed(1)} kg`:'—';
 let filled=0,total=bodyMetrics.length*4+4*4+2*3+3; bodyMetrics.forEach(([k])=>days.forEach(d=>{if(getPath(x,`body.${k}.${d}`)!==undefined&&getPath(x,`body.${k}.${d}`)!=='')filled++}));days.forEach(d=>{['water','sleepHours','sleepQuality','energy'].forEach(k=>{if(getPath(x,`lifestyle.${k}.${d}`))filled++})});['day1','day2','day3'].forEach(d=>{if(proteinTotal(d)>0)filled+=2;if((getPath(x,`feelings.${d}.checks`)||[]).length)filled++});let pct=Math.min(100,Math.round(filled/total*100));$('#completionText').textContent=`${pct}%`;$('#completionBar').style.width=`${pct}%`;
 $('#daySummary').innerHTML=days.map(d=>{let w=getPath(x,`body.weight.${d}`),water=getPath(x,`lifestyle.water.${d}`);return`<div class="day-pill"><b>${labels[d]}</b><small>${w?`${w} kg`:'未填體重'}<br>${water?`${water} cc`:'未填飲水'}</small></div>`}).join('');
 $('#comparisonGrid').innerHTML=bodyMetrics.map(([k,n,u])=>{let a=num(getPath(x,`body.${k}.before`)),b=num(getPath(x,`body.${k}.day3`)),diff=a&&b?b-a:null;return`<div class="compare-item"><span>${n}</span><b>${diff===null?'—':`${diff>0?'+':''}${Number.isInteger(diff)?diff:diff.toFixed(1)} ${u}`}</b></div>`}).join('');
 ['day1','day2','day3'].forEach((d,i)=>{$(`#proteinTotal${i+1}`).textContent=`${proteinTotal(d).toFixed(1)} 份`});$('#proteinStatus').innerHTML=['day1','day2','day3'].map(d=>{let t=proteinTotal(d),ok=c.servings&&t>=c.servings*.9;return`<div class="status-card ${ok?'good':t?'low':''}"><b>${labels[d]}：${t.toFixed(1)} 份</b><small>${!c.servings?'請先輸入體重':ok?'接近／達到建議量':`距建議量約 ${(Math.max(0,c.servings-t)).toFixed(1)} 份`}</small></div>`}).join('');
 renderReport();
}
function renderReport(){let x=p(),c=calc();$('#reportName').textContent=x.name||'—';$('#reportAge').textContent=x.age||'—';$('#reportWater').textContent=c.water?`${c.water.toLocaleString()} cc`:'—';$('#reportProtein').textContent=c.servings?`${c.servings.toFixed(1)} 份`:'—';$('#reportDate').textContent=x.startDate||'—';$('#reportBodyRows').innerHTML=bodyMetrics.map(([k,n,u])=>`<tr><th>${n}<small>${u}</small></th>${days.map(d=>`<td>${format(getPath(x,`body.${k}.${d}`))}</td>`).join('')}</tr>`).join('');$('#reportLifestyle').innerHTML=['day1','day2','day3'].map(d=>`<div class="report-mini"><b>${labels[d]}</b>飲水：${format(getPath(x,`lifestyle.water.${d}`),' cc')}<br>排便：${(getPath(x,`lifestyle.bowel.${d}`)||[]).join('、')||'—'}<br>睡眠：${format(getPath(x,`lifestyle.sleepHours.${d}`),' 小時')}／${getPath(x,`lifestyle.sleepQuality.${d}`)||'—'}<br>精神：${getPath(x,`lifestyle.energy.${d}`)||'—'}</div>`).join('');$('#reportProteinGrid').innerHTML=['day1','day2','day3'].map(d=>`<div class="report-mini"><b>${labels[d]}</b>N4：${format(getPath(x,`protein.n4.${d}`),' 份')}<br>食物：${format(getPath(x,`protein.food.${d}`),' 份')}<br>合計：${proteinTotal(d).toFixed(1)} 份</div>`).join('');$('#reportFeelings').innerHTML=['day1','day2','day3'].map(d=>`<div class="report-mini"><b>${labels[d]}</b>${(getPath(x,`feelings.${d}.checks`)||[]).join('、')||'—'}${getPath(x,`feelings.${d}.other`)?`<br>其他：${escapeHtml(getPath(x,`feelings.${d}.other`))}`:''}</div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderInputs();renderDerived();showView(state.currentView||'dashboard',false)}
function showView(v,save=true){state.currentView=v;$$('.view').forEach(e=>e.classList.toggle('active',e.id===`view-${v}`));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(save)persist();$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function cloneForExport(el){let clone=el.cloneNode(true);clone.querySelectorAll('.no-export,button').forEach(e=>e.remove());clone.querySelectorAll('input,textarea,select').forEach(ctrl=>{let span=document.createElement('span');span.className='export-value';if(ctrl.type==='checkbox'||ctrl.type==='radio')span.textContent=ctrl.checked?`☑ ${ctrl.value}`:'☐';else if(ctrl.tagName==='SELECT')span.textContent=ctrl.selectedOptions[0]?.textContent||'—';else span.textContent=ctrl.value||'—';ctrl.replaceWith(span)});return clone}
async function captureCurrent(){let source=$('.view.active');let host=document.createElement('div');host.style.cssText='position:fixed;left:-100000px;top:0;width:794px;background:white;z-index:-1';let clone=cloneForExport(source);clone.style.cssText+=';display:block;width:794px;min-height:1123px;border:0;box-shadow:none;border-radius:0;padding:28px';host.append(clone);document.body.append(host);try{return await html2canvas(clone,{scale:2,useCORS:true,backgroundColor:'#fff',windowWidth:794,scrollX:0,scrollY:0})}finally{host.remove()}}
function filename(ext){let title=$$(`#nav button`).find(b=>b.dataset.view===state.currentView)?.textContent.trim().replace(/^\S+\s*/,'')||'紀錄';return `傳奇健康管理學院_${safe(p().name||p().label)}_${safe(title)}.${ext}`}
async function exportPNG(share=false){$('#exportMask').classList.add('show');try{let canvas=await captureCurrent(),blob=await new Promise(r=>canvas.toBlob(r,'image/png',1)),file=new File([blob],filename('png'),{type:'image/png'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'傳奇健康管理學院紀錄',files:[file]});return}let a=document.createElement('a');a.download=file.name;a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast('PNG 已下載')}finally{$('#exportMask').classList.remove('show')}}
async function exportPDF(share=false){$('#exportMask').classList.add('show');try{let canvas=await captureCurrent(),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),pw=210,ph=297,margin=6,usableW=pw-margin*2,usableH=ph-margin*2,imgW=usableW,imgH=canvas.height*imgW/canvas.width,img=canvas.toDataURL('image/jpeg',.94);if(imgH<=usableH){pdf.addImage(img,'JPEG',margin,margin,imgW,imgH)}else{let pageCanvas=document.createElement('canvas'),ctx=pageCanvas.getContext('2d'),pxPerMm=canvas.width/usableW,pageHpx=Math.floor(usableH*pxPerMm);pageCanvas.width=canvas.width;let y=0,page=0;while(y<canvas.height){let slice=Math.min(pageHpx,canvas.height-y);pageCanvas.height=slice;ctx=pageCanvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,pageCanvas.width,pageCanvas.height);ctx.drawImage(canvas,0,y,canvas.width,slice,0,0,canvas.width,slice);if(page++)pdf.addPage();pdf.addImage(pageCanvas.toDataURL('image/jpeg',.94),'JPEG',margin,margin,usableW,slice/pxPerMm);y+=slice}}let blob=pdf.output('blob'),file=new File([blob],filename('pdf'),{type:'application/pdf'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'傳奇健康管理學院紀錄',files:[file]});return}pdf.save(file.name);toast('PDF 已下載')}finally{$('#exportMask').classList.remove('show')}}
function backup(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`傳奇健康管理學院_資料備份_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x?.profiles||x.profiles.length!==11)throw 0;if(!confirm('確定以備份檔覆蓋目前全部資料？'))return;state=x;persist();render();toast('還原完成')}catch{alert('備份檔格式不正確')}};r.readAsText(file)}
build();render();
$('#clientSelect').addEventListener('change',e=>{state.active=+e.target.value;persist();render()});$$('#nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#quickSaveBtn').addEventListener('click',()=>persist(true));$('#exportPngBtn').addEventListener('click',()=>exportPNG());$('#exportPdfBtn').addEventListener('click',()=>exportPDF());$('#shareBtn').addEventListener('click',async()=>{try{await exportPDF(true)}catch(e){if(e?.name!=='AbortError'){toast('此裝置不支援 PDF 分享，改分享 PNG');try{await exportPNG(true)}catch{}}}});$('#clearClientBtn').addEventListener('click',()=>{if(confirm('確定清除此組客戶全部資料？此動作無法復原。')){state.profiles[state.active]=defaultProfile(state.active);persist();render();toast('已清除')}});$('#backupBtn').addEventListener('click',backup);$('#restoreInput').addEventListener('change',e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
